base_lr: 0.01
batch_size: 32
config: ./dgnn/config/nturgbd-cross-view/test_spatial.yaml
cpu: false
device:
- 0
eval_interval: 5
feeder: feeders.feeder.Feeder
freeze_graph_until: 10
ignore_weights: []
log_interval: 100
model: model.dgnn.Model
model_args:
  graph: graph.directed_ntu_rgb_d.Graph
  num_class: 60
  num_person: 2
  num_point: 25
model_saved_name: ./model_save
nesterov: true
num_epoch: 120
num_worker: 8
optimizer: SGD
phase: test
print_log: true
save_interval: 2
save_score: true
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 60
- 90
test_batch_size: 32
test_feeder_args:
  bone_data_path: ./dgnn/data/test_data_bone.npy
  debug: false
  joint_data_path: ./dgnn/data/test_data_joint.npy
  label_path: ./dgnn/data/test_label.pkl
train_feeder_args: {}
weight_decay: 0.0001
weights: ./dgnn/weights/-1-1176.pt
work_dir: ./workspace/
